spring:
  application:
    name: raf-example-dubbo-provider

server:
  port: 8081

dubbo:
  registry:
    address: nacos://${NACOS_ADDR:127.0.0.1:8848}
    parameters:
      namespace: ${NACOS_NAMESPACE:public}
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: io.github.jerryraf.examples.dubbo.provider
