spring:
  application:
    name: dubbo-consumer-example

server:
  port: 8082

dubbo:
  registry:
    address: nacos://${NACOS_ADDR:127.0.0.1:8848}
    parameters:
      namespace: ${NACOS_NAMESPACE:public}
  consumer:
    check: false
