<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.jerryraf</groupId>
        <artifactId>raf-framework-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../raf-framework-parent</relativePath>
    </parent>

    <groupId>io.github.jerryraf.examples</groupId>
    <artifactId>raf-examples</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>RAF Examples</name>
    <description>Aggregator for all raf-framework example projects</description>

    <modules>
        <module>raf-example-web-starter</module>
        <module>raf-example-gateway-starter</module>
        <module>raf-example-redis-starter</module>
        <module>raf-example-rabbit-starter</module>
        <module>raf-example-rocketmq-starter</module>
        <module>raf-example-kafka-starter</module>
        <module>raf-example-mybatis-starter</module>
        <module>raf-example-shardingsphere-starter</module>
        <module>raf-example-nacos-starter</module>
        <module>raf-example-mongodb-starter</module>
        <module>raf-example-elasticsearch-starter</module>
        <module>raf-example-openapi-starter</module>
        <module>raf-example-dubbo-starter</module>
        <module>raf-example-okhttp-starter</module>
        <module>raf-example-sentry-starter</module>
        <module>raf-example-monitor-starter</module>
        <module>raf-example-kms-starter</module>
    </modules>
</project>
