<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>raf-framework-parent</artifactId>
    <name>raf-framework-parent</name>
    <description>raf-framework-parent</description>
    <packaging>pom</packaging>
    <version>${revision}</version>

    <parent>
        <groupId>io.github.jerryraf</groupId>
        <artifactId>raf-framework-dependencies</artifactId>
        <version>3.0.0</version>
        <relativePath>../raf-framework-dependencies</relativePath>
    </parent>

    <properties>
        <revision>3.0.0</revision>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!--raf framework internal modules-->
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-web-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-datasource-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-mybatis-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-redis-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-okhttp-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-sentry-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-dubbo-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-rabbit-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-swagger-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-nacos-config-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-nacos-discovery-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-monitor-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-gateway-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-rocketmq-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-kafka-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-elasticsearch-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-mongodb-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jerryraf</groupId>
                <artifactId>raf-framework-shardingsphere-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <parameters>true</parameters>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <inherited>false</inherited>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
